config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/show'
  # get 'carpets/index'
  # get 'carpets/new'
  # get 'carpets/create'
  # get 'carpets/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "carpets#index"

  resources :carpets do
    # resources :reviews, only: [:create, :destroy, :edit, :update]
    resources :bookings, only: [:new, :create] do
      # resources :reviews, only: [:new]
    end
  end
  resources :bookings, only: [:edit, :update]
  delete "/bookings/:id", to: "bookings#destroy", as: :delete_booking
  resources :dashboards, only: [:show]
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "carpets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :carpet
  validates :booked_from, presence: true
  validates :booked_until, presence: true
  validates :user_id, presence: true
  validates :carpet_id, presence: true
end

app/models/carpet.rb
class Carpet < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :condition, presence: true, inclusion: { in: %w(poor slightly\ used good like\ new) }
  validates :description, length: { minimum: 3, maximum: 500 }, allow_blank: true
  validates :address, presence: true
  validates :user_id, presence: true
  validates :price, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_details,
  against: [ :name, :description, :address, :condition ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carpets
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :index
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_bookings, only: [:show, :edit, :update, :destroy]

  def new
    @booking = Booking.new
    @carpet = Carpet.find(params[:carpet_id])
    @carpet_bookings = []
    @carpet.bookings.each do |booking|
      @carpet_bookings << {from: booking.booked_from, to: booking.booked_until}
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @carpet = Carpet.find(params[:carpet_id])
    @booking.carpet = @carpet
     if @booking.save
      redirect_to dashboards_show_path
     else
      render :new
     end
  end

  def edit
    @carpet = Carpet.find(@booking.carpet.id)
    @carpet_bookings = []
    @carpet.bookings.each do |booking|
    @carpet_bookings << {from: booking.booked_from, to: booking.booked_until}
    end
  end

  def destroy
    @booking.destroy
    redirect_to dashboards_show_path, status: :see_other
  end

  def update
    @booking.update(booking_params)
    redirect_to dashboards_show_path
  end

  private

  def booking_params
    params.require(:booking).permit(:booked_until, :booked_from, :rating)
  end

  def set_bookings
    @booking = Booking.find(params[:id])
  end
end

app/controllers/carpets_controller.rb
class CarpetsController < ApplicationController
  before_action :set_carpets, only: [:show, :edit, :update, :destroy]
  def index
    if params[:query].present?
      @carpets = Carpet.search_by_details(params[:query])
    else
      @carpets = Carpet.all.reverse
    end
  end

  def show
  end

  def new
    @carpet = Carpet.new
  end

  def create
    @carpet = Carpet.new(carpet_params)
    @carpet.user = current_user
    @carpet.save!
    redirect_to carpet_path(@carpet)
  end

  def edit
  end

  def update
    @carpet.update(carpet_params)
    redirect_to carpet_path(@carpet)
  end

  def destroy
    @carpet.destroy
    redirect_to carpets_path, status: :see_other
  end

  private

  def carpet_params
    params.require(:carpet).permit(:name, :description, :condition, :address, :available, :user_id, :photo, :price)
  end

  def set_carpets
    @carpet = Carpet.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @carpets = current_user.carpets
    @bookings = current_user.bookings
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="form-container" data-controller="datepickr" data-datepickr-availability-value="<%= @carpet_bookings.to_json %>">
<%= simple_form_for(@booking) do |f| %>
  <%= f.input :booked_from, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :booked_until, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.submit class:"btn btn-dark" %>
<% end %>
</div>

app/views/bookings/new.html.erb
<div class="form-container" data-controller="datepickr" data-datepickr-availability-value="<%= @carpet_bookings.to_json %>">
<%= simple_form_for([@carpet, @booking]) do |f| %>
  <%= f.input :booked_from, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :booked_until, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.submit class:"btn btn-dark" %>
<% end %>
</div>

app/views/carpets/_form.html.erb
<%= simple_form_for(carpet) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :condition, collection: ["poor", "slightly used", "good", "like new"] %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class:"btn btn-dark" %>
<% end %>

app/views/carpets/create.html.erb
<h1>Carpets#create</h1>
<p>Find me in app/views/carpets/create.html.erb</p>

app/views/carpets/edit.html.erb
<div class="form-container">
  <h1 class="form-title">Update the carpet´s details</h1>
  <%= render "form", carpet: @carpet %>
</div>

app/views/carpets/index.html.erb
 <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1560807454-c23ba0bfa2bb?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872);">
    <div class="banner-text">
      <h1><strong>Welcome to Aladinaba</strong></h1>
      <br>
      <p>Rent a beautiful carpet for a day</p>
    </div>
</div>

<div class="search d-flex">
  <h1 class="page-title">Discover carpets around you</h1>
  <%= form_tag carpets_path, method: :get, class: "d-flex search-bar" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a carpet"
    %>
    <%= submit_tag "Search", class: "btn btn-dark" %>
  <% end %>
</div>

<div class="container-cards" id="index-container">
  <% @carpets.each do |carpet| %>
    <%= link_to carpet_path(carpet), class: "text-decoration-none link-dark" do %>
    <div class="cards">
      <% if carpet.photo.attached? %>
          <%= cl_image_tag carpet.photo.key, width: 250, crop: :fill %>
      <% end %>
      <div class="card-body">
          <h3><%= carpet.name %></h3>
          <p><%= carpet.condition %></p>
          <p><%= carpet.address %></p>
          <p id="index-price">$ <%= carpet.price.to_i%> day</p>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/carpets/new.html.erb
<div class="form-container">
  <h1 class="form-title">Add a new carpet</h1>
  <%= render "form", carpet: @carpet %>
</div>

app/views/carpets/show.html.erb
<div class="container-sm">

  <div class="p-1 show-container d-flex justify-center">
    <div class="w-50">
      <% if @carpet.photo.attached? %>
        <%= cl_image_tag @carpet.photo.key, height: 300, crop: :fill, class: "cards show-img w-100" %>
      <% else %>
      <%# @carpet.photo.attached = "https://images.unsplash.com/photo-1588421874990-1fe162747f9b?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387" %>
        <%= image_tag "https://images.unsplash.com/photo-1588421874990-1fe162747f9b?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387", class: "rounded-3", style:"height:300px;object-fit: cover;" %>
      <% end %>
    </div>
    <div class="w-50 card-position2">
      <div class="card-position">
          <ul class="text-start list-unstyled">
            <li><h1><%= @carpet.name %></h1></li>
            <li><div class= "fas fa-map-marker-alt"> - </div><%= @carpet.address %></li>
            <br>
            <li>Posted by: <%= @carpet.user.first_name %> <%= @carpet.user.last_name %></li>
            <li>Condition: <%= @carpet.condition %></li>
            <br>
            <li class="card-text text-start"><p><%= @carpet.description %></p></li>
            <li id="price-show"><strong>$<%= @carpet.price.to_i %>/day</strong></li>
          </ul>
          <div class="d-flex my-5">
            <% if current_user == @carpet.user %>
              <%= link_to "Edit", edit_carpet_path(@carpet), class: "btn btn-dark text-start" %>
              <%= link_to "Delete", carpet_path(@carpet), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-dark text-start mx-2" %>
            <% else %>
              <%= link_to "Book", new_carpet_booking_path(@carpet),class: "btn btn-dark text-start" %>
            <% end %>
          </div>
        </div>
      </div>
      </div>
  <div>
</div>
<%# Here my comments %>

app/views/dashboards/show.html.erb
 <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1560807454-c23ba0bfa2bb?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872);">
    <div class="banner-text">
      <h1><strong>My dashboard</strong></h1>
      <br>
      <br>
    </div>
</div>

<div class="page-title"><h1>My Carpets</h1></div>

<div class="container-cards dashboard-contaner">
  <% current_user.carpet_ids.each do |carpet_id| %>
    <% carpet = Carpet.find(carpet_id)%>
    <div class="cards cards-dashboard">
      <% if carpet.photo.attached? %>
        <%= cl_image_tag carpet.photo.key, width: 250, crop: :fill %>
      <% end %>

  <%= link_to carpet_path(carpet), class: "text-decoration-none link-dark" do %>
      <div class="card-body">
        <h3><%= carpet.name%></h3>
        <p><%= carpet.condition%></p>
        <p><%= carpet.address%></p>
        <p id="index-price">$ <%= carpet.price.to_i%> day</p>

        <br>

        <%= link_to "Delete", carpet_path(carpet_id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-dark" %>
        <%= link_to "Edit", edit_carpet_path(carpet_id), class: "btn btn-dark" %>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

<br>
<hr>

<div class="page-title"><h1>My Bookings</h1></div>

<div class="container-cards dashboard-contaner">
  <% current_user.booking_ids.each do |booking_id| %>
    <% booking = Booking.find(booking_id) %>
    <div class="cards cards-dashboard">

        <% if booking.carpet.photo.attached? %>
          <%= cl_image_tag booking.carpet.photo.key, width: 250, crop: :fill %>
        <% end %>

      <div class="card-body">
        <% total_booking_time =  booking.booked_until - booking.booked_from%>
        <h3> <%= booking.carpet.name %></h3>
        <p>Booked from:
        <br>
        <%= booking.booked_from %> to <%= booking.booked_until %></p>
        <p id="index-price"> Total $ <%= (booking.carpet.price * (total_booking_time.to_i + 1)).to_i %></p>

        <br>

        <%= link_to "Delete", delete_booking_path(booking_id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-dark" %>
        <%= link_to "Edit", edit_booking_path(booking_id), class: "btn btn-dark" %>
      </div>

    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ALADINABA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100&display=swap" rel="stylesheet">
  </head>

  <body>
      <div class="page-container">
        <div class="navbar-container"><%= render "shared/navbar" %></div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <div class="main-page-container">
          <%= yield %>
        </div>
        <div class="footer-container"><%= render "shared/footer" %></div>
      </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
</div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by the <strong>Livecode team</strong>.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to carpets_path, class: "navbar-brand" do %>
      <h1><%= image_tag "magic-carpet.png" %> ALADINABA</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", carpets_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboards_show_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to 'Add Carpet', new_carpet_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

</div>